# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IO-Capture-Stdout-Extended
version:      0.04
version_from: lib/IO/Capture/Stdout/Extended.pm
installdirs:  site
requires:
    IO::Capture:                   0.03
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
